[package]
name = "castle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.0", features = ["png", "bevy_pbr"] }
bevy_ecs_tilemap = "0.9.0"
bevy_hanabi = "0.6.2"
bevy_mod_picking = "0.12.0"
bevy_rapier3d = { version = "0.21.0", features = ["debug-render"] }
iyes_loopless = { version = "0.9.1", features = ["states"] }

# Add this to your Cargo.toml
[profile.dev.package.bevy_rapier3d]
opt-level = 3
